yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр поста
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Новый пост
    path('create/', views.post_create, name='post_create'),
    # Редактирование поста
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Страница группы
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Добавление комментария к посту
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    # Страница постов автора, на которых подписан пользователь
    path('follow/', views.follow_index, name='follow_index'),
    # Подписка на автора
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    # Отписка от автора
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]

handler404 = 'core.views.page_not_found'

handler403 = 'core.views.csrf_failure'

handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}            
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/forms_body.html
{% load user_filters %}
  <div class="form-group row my-3"
    {% if field.field.required %} 
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
    {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>

yatube/templates/includes/header.html
{% load static %}
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>
          <ul class="nav nav-pills">
            {% with request.resolver_match.view_name as view_name %} 
              <!-- пункты меню видны всем -->
              {% if view_name != 'posts:index' %}
                <li class="nav-item"> 
                  <a class="nav-link"
                    href="{% url 'posts:index' %}"
                  >
                    На главную
                  </a>
                </li>
              {% endif %}
              <li class="nav-item"> 
                <a class="nav-link" {% if view_name  == 'about:author' %}active{% endif %}
                  href="{% url 'about:author' %}"
                >
                  Об авторе
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" {% if view_name  == 'about:tech' %}active{% endif %}
                  href="{% url 'about:tech' %}"
                >
                  Технологии
              </a>
              </li>
              <!-- пункты меню видны только авторизованному пользователю -->
              {% if user.is_authenticated %}
              <li class="nav-item"> 
                <a class="nav-link" {% if view_name  == 'posts:post_create' %}active{% endif %}
                  href="{% url 'posts:post_create' %}"
                >
                  Новая запись
              </a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link link-light" {% if view_name  == 'users:password_reset' %}active{% endif %}
                  href="{% url 'users:password_reset' %}"
                >
                  Изменить пароль
              </a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link link-light" {% if view_name  == 'users:logout' %}active{% endif %}
                  href="{% url 'users:logout' %}"
                >
                  Выйти
                </a>
              </li>
              <li>
                Пользователь: {{ user.username }}
              </li>
              <!-- пункты меню видны только неавторизованному пользователю -->
              {% else %}
              <li class="nav-item"> 
                <a class="nav-link link-light" {% if view_name  == 'users:login' %}active{% endif %}
                  href="{% url 'users:login' %}"
                >
                  Войти
                </a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link link-light" {% if view_name  == 'users:signup' %}active{% endif %}
                  href="{% url 'users:signup' %}"
                >
                  Регистрация
                </a>
              </li>
              {% endif %}
            {% endwith %}
          </ul>
        </div>
      </nav>     
    </header>

yatube/templates/includes/post_card.html
{% load thumbnail %}
<article>
<ul>
  {% if 'profile' not in request.path %}
  <li>
    Автор: {{ post.author.get_full_name }}
    <a href="{% url 'posts:profile' post.author %}">
      все посты пользователя
    </a>
  </li>
  {% endif %}
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }} 
  </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  <div class="row">
    <div class="col-3">
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    </div> 
    <div class="col-9">
      {%if post.group%}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
    </div>
  </div>
  {%if not forloop.last%} <hr> {% endif %}
</article>